name: 🪲 Bug report
description: Report bugs and errors
title: "[BUG] "
labels: ["bug"]
assignees:
  - tech5g5g
body:
  - type: checkboxes
    attributes:
      label: "I have checked:"
      options:
        - label: This is not a duplicate of another issue
          required: true
        - label: This is not an feature request
          required: true
  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Specifications
      description: Your OS and edition, OS version, and CPU name.
      placeholder: |
        OS: [e.g. Windows 11 Home, Windows 10 Pro]
        Version: [XXXXX.XXXX]
        CPU: [e.g. Intel, AMD]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Addtional context
      description: Any other context about the problem.
    validations:
      required: false
      
